### ISSUE TITLE
mac好像不行耶

### ISSUE THREAD

**Issue by MathrewLing** [CamuseCao/XMU-Thesis-Overleaf#1]

**Comment by CamuseCao** [comment]
感谢你的使用反馈，请下载[该地址]{https://github.com/CamuseCao/XMU-Undergraduate-thesis-template }下的最新文件。
再打开`Settings/Seetting.tex`文件，把89-91这三行代码注释掉，然后把93-95行的代码去掉注释，即可运行。
今天发现我虚拟机上的Mac有问题，安装了好久，没有及时解决这个问题。如果仍然不能运行，请把你的TeX发行版本，编译方式以及报错内容反馈给我。
